<?php
/**
 * RoomOptionsDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Apache OpenMeetings API
 *
 * Integration API enables to connect to an OpenMeetings instance, eg for generating users, create links to directly access conference rooms.<br/><br/>         <b>It is mainly designed for Server2Server integration, for example to integrate into your website, CMS or 3rd party application</b><br/><br/>         For examples how to use the Rest API see <a href=\"https://openmeetings.apache.org/RestAPISample.html\" target=\"_BLANK\">https://openmeetings.apache.org/RestAPISample.html</a>.<br/><br/>         Community contributed modules for using this API include for example:         <ul>          <li><a href=\"https://openmeetings.apache.org/RestAPISample.html#how-to-integrate-using-nodejs\" target=\"_BLANK\"> Node.js module for using API</a></li>         </ul>         Other community plugins using this API for Moodle, SugarCRM, Drupal, Joomla can be found in the Configuration>Plugins section at <a href=\"https://openmeetings.apache.org\" target=\"_BLANK\">https://openmeetings.apache.org</a>
 *
 * OpenAPI spec version: 7.0.0-SNAPSHOT
 * Contact: dev@openmeetings.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RoomOptionsDTO Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoomOptionsDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoomOptionsDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'allow_recording' => 'bool',
'allow_same_url_multiple_times' => 'bool',
'external_room_id' => 'string',
'external_type' => 'string',
'moderator' => 'bool',
'recording_id' => 'int',
'room_id' => 'int',
'show_audio_video_test' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'allow_recording' => null,
'allow_same_url_multiple_times' => null,
'external_room_id' => null,
'external_type' => null,
'moderator' => null,
'recording_id' => 'int64',
'room_id' => 'int64',
'show_audio_video_test' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allow_recording' => 'allowRecording',
'allow_same_url_multiple_times' => 'allowSameURLMultipleTimes',
'external_room_id' => 'externalRoomId',
'external_type' => 'externalType',
'moderator' => 'moderator',
'recording_id' => 'recordingId',
'room_id' => 'roomId',
'show_audio_video_test' => 'showAudioVideoTest'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allow_recording' => 'setAllowRecording',
'allow_same_url_multiple_times' => 'setAllowSameUrlMultipleTimes',
'external_room_id' => 'setExternalRoomId',
'external_type' => 'setExternalType',
'moderator' => 'setModerator',
'recording_id' => 'setRecordingId',
'room_id' => 'setRoomId',
'show_audio_video_test' => 'setShowAudioVideoTest'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allow_recording' => 'getAllowRecording',
'allow_same_url_multiple_times' => 'getAllowSameUrlMultipleTimes',
'external_room_id' => 'getExternalRoomId',
'external_type' => 'getExternalType',
'moderator' => 'getModerator',
'recording_id' => 'getRecordingId',
'room_id' => 'getRoomId',
'show_audio_video_test' => 'getShowAudioVideoTest'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['allow_recording'] = isset($data['allow_recording']) ? $data['allow_recording'] : null;
        $this->container['allow_same_url_multiple_times'] = isset($data['allow_same_url_multiple_times']) ? $data['allow_same_url_multiple_times'] : null;
        $this->container['external_room_id'] = isset($data['external_room_id']) ? $data['external_room_id'] : null;
        $this->container['external_type'] = isset($data['external_type']) ? $data['external_type'] : null;
        $this->container['moderator'] = isset($data['moderator']) ? $data['moderator'] : null;
        $this->container['recording_id'] = isset($data['recording_id']) ? $data['recording_id'] : null;
        $this->container['room_id'] = isset($data['room_id']) ? $data['room_id'] : null;
        $this->container['show_audio_video_test'] = isset($data['show_audio_video_test']) ? $data['show_audio_video_test'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allow_recording
     *
     * @return bool
     */
    public function getAllowRecording()
    {
        return $this->container['allow_recording'];
    }

    /**
     * Sets allow_recording
     *
     * @param bool $allow_recording allow_recording
     *
     * @return $this
     */
    public function setAllowRecording($allow_recording)
    {
        $this->container['allow_recording'] = $allow_recording;

        return $this;
    }

    /**
     * Gets allow_same_url_multiple_times
     *
     * @return bool
     */
    public function getAllowSameUrlMultipleTimes()
    {
        return $this->container['allow_same_url_multiple_times'];
    }

    /**
     * Sets allow_same_url_multiple_times
     *
     * @param bool $allow_same_url_multiple_times allow_same_url_multiple_times
     *
     * @return $this
     */
    public function setAllowSameUrlMultipleTimes($allow_same_url_multiple_times)
    {
        $this->container['allow_same_url_multiple_times'] = $allow_same_url_multiple_times;

        return $this;
    }

    /**
     * Gets external_room_id
     *
     * @return string
     */
    public function getExternalRoomId()
    {
        return $this->container['external_room_id'];
    }

    /**
     * Sets external_room_id
     *
     * @param string $external_room_id external_room_id
     *
     * @return $this
     */
    public function setExternalRoomId($external_room_id)
    {
        $this->container['external_room_id'] = $external_room_id;

        return $this;
    }

    /**
     * Gets external_type
     *
     * @return string
     */
    public function getExternalType()
    {
        return $this->container['external_type'];
    }

    /**
     * Sets external_type
     *
     * @param string $external_type external_type
     *
     * @return $this
     */
    public function setExternalType($external_type)
    {
        $this->container['external_type'] = $external_type;

        return $this;
    }

    /**
     * Gets moderator
     *
     * @return bool
     */
    public function getModerator()
    {
        return $this->container['moderator'];
    }

    /**
     * Sets moderator
     *
     * @param bool $moderator moderator
     *
     * @return $this
     */
    public function setModerator($moderator)
    {
        $this->container['moderator'] = $moderator;

        return $this;
    }

    /**
     * Gets recording_id
     *
     * @return int
     */
    public function getRecordingId()
    {
        return $this->container['recording_id'];
    }

    /**
     * Sets recording_id
     *
     * @param int $recording_id recording_id
     *
     * @return $this
     */
    public function setRecordingId($recording_id)
    {
        $this->container['recording_id'] = $recording_id;

        return $this;
    }

    /**
     * Gets room_id
     *
     * @return int
     */
    public function getRoomId()
    {
        return $this->container['room_id'];
    }

    /**
     * Sets room_id
     *
     * @param int $room_id room_id
     *
     * @return $this
     */
    public function setRoomId($room_id)
    {
        $this->container['room_id'] = $room_id;

        return $this;
    }

    /**
     * Gets show_audio_video_test
     *
     * @return bool
     */
    public function getShowAudioVideoTest()
    {
        return $this->container['show_audio_video_test'];
    }

    /**
     * Sets show_audio_video_test
     *
     * @param bool $show_audio_video_test show_audio_video_test
     *
     * @return $this
     */
    public function setShowAudioVideoTest($show_audio_video_test)
    {
        $this->container['show_audio_video_test'] = $show_audio_video_test;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
